# Generated by Django 6.0.6 on 2026-06-09 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Postagem',
                'verbose_name_plural': 'Postagens',
            },
        ),
        migrations.CreateModel(
            name='UpdateNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('STA', 'STA'), ('SGEO', 'SGEO'), ('SHP', 'SHP'), ('SGESTAO', 'SGESTAO')], max_length=50, verbose_name='Sistema')),
                ('version', models.CharField(max_length=20, verbose_name='Versão')),
                ('date', models.DateField(verbose_name='Data de Atualização')),
                ('details', models.TextField(verbose_name='Detalhes da Atualização (Use formato de lista)')),
            ],
            options={
                'verbose_name': 'Nota de Atualização',
                'verbose_name_plural': 'Notas de Atualização',
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título do Vídeo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('video_file', models.FileField(help_text='Faça o upload do arquivo MP4 aqui.', upload_to='videos/', verbose_name='Arquivo de Vídeo (Upload)')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/', verbose_name='Capa do Vídeo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vídeo Tutorial',
                'verbose_name_plural': 'Vídeos Tutoriais',
            },
        ),
    ]
