# Generated by Django 6.0.6 on 2026-06-10 00:20

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DynamicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título da Página')),
                ('slug', models.SlugField(blank=True, help_text='A URL da página. Ex: contato-corporativo', max_length=255, unique=True)),
                ('icon', models.CharField(blank=True, help_text='Ex: fas fa-file-alt (opcional)', max_length=50, verbose_name='Ícone FontAwesome')),
                ('content', tinymce.models.HTMLField(verbose_name='Conteúdo da Página')),
                ('is_active', models.BooleanField(default=True, verbose_name='Publicada?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Página Dinâmica',
                'verbose_name_plural': 'Páginas Dinâmicas',
            },
        ),
    ]
