# Generated by Django 6.0.6 on 2026-06-10 00:26

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_dynamicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='videotutorial',
            name='caption',
            field=models.TextField(blank=True, verbose_name='Texto da Legenda (Abaixo do vídeo)'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='icon',
            field=models.CharField(blank=True, help_text='Ex: 🎬', max_length=10, verbose_name='Emoji do Botão'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='short_title',
            field=models.CharField(default='Novo Vídeo', help_text='Ex: Apresentação', max_length=50, verbose_name='Título Curto (para o botão)'),
        ),
        migrations.AddField(
            model_name='videotutorial',
            name='slug',
            field=models.SlugField(default='video', help_text='Ex: apresentacao (usado para o link interno)', unique=True),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Texto Explicativo (Aceita formatação e listas)'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Título Completo (ex: 01 — Apresentação)'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='video_file',
            field=models.FileField(help_text='Faça o upload do arquivo MP4 direto aqui.', upload_to='videos/', verbose_name='Arquivo de Vídeo (.mp4)'),
        ),
    ]
