# Generated by Django 6.0.6 on 2026-06-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_videotutorial_caption_videotutorial_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title_1', models.CharField(default='Inovação e Tecnologia para o', max_length=100, verbose_name='Título Principal (Parte 1)')),
                ('hero_title_highlight', models.CharField(default='Seu Negócio', max_length=100, verbose_name='Título em Destaque (Azul)')),
                ('hero_subtitle', models.TextField(default='Oferecendo soluções de tecnologia para otimizar processos e garantir a segurança da sua empresa.', verbose_name='Subtítulo Principal')),
                ('hero_btn_text', models.CharField(default='Ver Nossas Soluções', max_length=50, verbose_name='Texto do Botão Principal')),
                ('hero_btn_link', models.CharField(default='#servicos', max_length=100, verbose_name='Link do Botão Principal')),
                ('services_title', models.CharField(default='Nossas Soluções', max_length=100, verbose_name='Título da Seção de Soluções')),
                ('services_subtitle', models.TextField(default='Especialistas em transformar desafios em resultados digitais.', verbose_name='Subtítulo da Seção de Soluções')),
                ('service1_icon', models.CharField(default='fas fa-code', max_length=50, verbose_name='Ícone do Cartão 1')),
                ('service1_title', models.CharField(default='Software', max_length=100, verbose_name='Título do Cartão 1')),
                ('service1_desc', models.TextField(default='Sistemas personalizados focados na experiência do Cliente.', verbose_name='Descrição do Cartão 1')),
                ('service1_link', models.CharField(default='/software/', max_length=100, verbose_name='Link do Cartão 1')),
                ('service2_icon', models.CharField(default='fas fa-server', max_length=50, verbose_name='Ícone do Cartão 2')),
                ('service2_title', models.CharField(default='Infraestrutura & Cloud', max_length=100, verbose_name='Título do Cartão 2')),
                ('service2_desc', models.TextField(default='Segurança e alta disponibilidade para sua rede e servidores.', verbose_name='Descrição do Cartão 2')),
                ('service2_link', models.CharField(default='/infraestrutura/', max_length=100, verbose_name='Link do Cartão 2')),
                ('service3_icon', models.CharField(default='fas fa-bullhorn', max_length=50, verbose_name='Ícone do Cartão 3')),
                ('service3_title', models.CharField(default='Marketing', max_length=100, verbose_name='Título do Cartão 3')),
                ('service3_desc', models.TextField(default='Estratégias digitais e presença online para o seu negócio.', verbose_name='Descrição do Cartão 3')),
                ('service3_link', models.CharField(default='/marketing/', max_length=100, verbose_name='Link do Cartão 3')),
            ],
            options={
                'verbose_name': 'Conteúdo da Home',
                'verbose_name_plural': 'Conteúdo da Home',
            },
        ),
    ]
